event1 = Event.create({name: "Your biggest city is hit by Hurricane Donald! Public emergency declared. City requesting help from Nation."})
event1.responses.create(description: "Declare a state of emergency. Divert all available resources to helping the affected. Support telethon drive hosted by Taylor Swift. Experts say this course of action will increase stability.", capital_effect: 50, population_effect: 250000, stability_effect: 0.1, resources_effect: 1000, nation_id: 1)
event1.responses.create(description: "Call the Red Cross. Let them handle it, they're the experts. Support telethon drive hosted by Kanye West. Experts say this course of action will result in no deaths", capital_effect: -10, population_effect: 0, stability_effect: 0, resources_effect: -250, nation_id: 1)
event1.responses.create(description: "Do nothing. Let them fend for themselves. The market will correct for the disaster. Advisers say this decision will maintain resources.", capital_effect: -50, population_effect: -100000, stability_effect: -0.2, resources_effect: 0, nation_id: 1)

event2 = Event.create({name: "Stock Market Crash. Panic reins supreme. Population worries about retirement resources."})
event2.responses.create(description: "Halt the markets for the day and give an inspiring speech. Work with Congress to create a stimulus package. Advisers say this will save capital.", capital_effect: 50, population_effect: 250000, stability_effect: 0.1, resources_effect: 1000, nation_id: 1)
event2.responses.create(description: "Give pretty okay speech at Goldman Sachs. Bailout the banks. Experts say this will help maintain stability.", capital_effect: -10, population_effect: 0, stability_effect: 0, resources_effect: -500, nation_id: 1)
event2.responses.create(description: "Dips and valleys are a part of a healthy economy. Ride the wave, fellas. Advisers say population size will be unaffected by this.", capital_effect: -50, population_effect: 0, stability_effect: -0.2, resources_effect: -1000, nation_id: 1)

event3 = Event.create({name: "Scientists discover a cure for the deadly Donald Trump Virus. Need funding for vaccine distribution."})
event3.responses.create(description: "Grant funding to the scientists, and set up a special panel to study the terrifying effects of this disease. Experts say this will save lives.", capital_effect: 50, population_effect: 250000, stability_effect: 0.1, resources_effect: 1000, nation_id: 1)
event3.responses.create(description: "Maintain current funding level and encourage private investment. Advisers say this will maintain population level.", capital_effect: -10, population_effect: 0, stability_effect: 0, resources_effect: -250, nation_id: 1)
event3.responses.create(description: "Vaccines cause austism, don't you know? Divert funds to charter schools instead. Advisers say this will maintain GDP.", capital_effect: 0, population_effect: -100000, stability_effect: -0.2, resources_effect: -1000, nation_id: 1)

event4 = Event.create({name: "New rocket has gone over budget. Local company requests additional government support. Space travel to Mars would inspire the population."})
event4.responses.create(description: "Grant funding and set goal to travel to Mars by 2030. Give classic speech about doing things because they are hard. The masses love it.", capital_effect: 50, population_effect: 250000, stability_effect: 0.1, resources_effect: 1000, nation_id: 1)
event4.responses.create(description: "Set goal to go to Mars by 2050. Encourage private investment. Watch the movie 'The Martian.' Experts say this will maintain stability.", capital_effect: -10, population_effect: 0, stability_effect: 0, resources_effect: -500, nation_id: 1)
event4.responses.create(description: "Mars is fictional, the Earth is the only real planet. Also, it's flat. Divert funds to voter suppression efforts. Advisers say that this will not effect population. Plus, you're the only person in existence so you're not too concerned about the population anyways.", capital_effect: -50, population_effect: 0, stability_effect: -0.2, resources_effect: -1000, nation_id: 1)
