Nation.create(name: "test", economy: "Capitalist", geography: "Plains", government: "Democracy")

event1 = Event.create({name: "Your biggest city is hit by Hurricane Donald! Public emergency declared. City requesting help from Nation."})
event1.responses.create(description: "Declare a state of emergency. Divert all available resources to helping the affected. Support telethon drive hosted by Taylor Swift. Experts say this course of action will increase stability.", capital_effect: 50, population_effect: 250000, stability_effect: 0.1, resources_effect: 1000, nation_id: 1)
event1.responses.create(description: "Call the Red Cross. Let them handle it, they're the experts. Support telethon drive hosted by Kanye West. Experts say this course of action will result in no deaths.", capital_effect: -10, population_effect: 0, stability_effect: 0, resources_effect: -250, nation_id: 1)
event1.responses.create(description: "Do nothing. Let them fend for themselves. The market will correct for the disaster. Advisers say this decision will maintain resources.", capital_effect: -50, population_effect: -100000, stability_effect: -0.2, resources_effect: 0, nation_id: 1)

event5 = Event.create({name: "The worst earthquake in North America in 350 years hits your state. Bridges collapse. Tsunmais roll in."})
event5.responses.create(description: "Declare a state of emergency. Divert all available resources to helping the affected. Get out and personally deliver supplies to those in need. Experts say this course of action will increase stability.", capital_effect: 50, population_effect: 250000, stability_effect: 0.1, resources_effect: 1000, nation_id: 1)
event5.responses.create(description: "Call Doctors Without Borders. Let them handle it, they're the experts. Experts say this course of action will result in no further deaths.", capital_effect: -10, population_effect: 0, stability_effect: 0, resources_effect: -250, nation_id: 1)
event5.responses.create(description: "Do nothing. Let them fend for themselves. The market will correct for the disaster. Advisers say this decision will maintain capital.", capital_effect: 0, population_effect: -100000, stability_effect: -0.2, resources_effect: -500, nation_id: 1)

event6 = Event.create({name: "Global warming suddenly accelerates. Water resources are diminishing. The public wants the government to act. "})
event6.responses.create(description: "Create a sun shield that orbits over your nation to lessen the effects of the sun and maintain water supplies. Create Universal Sunscreen Program for your people. Experts say this course of action will increase stability.", capital_effect: 50, population_effect: 250000, stability_effect: 0.1, resources_effect: 0, nation_id: 1)
event6.responses.create(description: "Call Al Gore. Think about possibly making a plan... sometime. Experts say this course of action will result in no further deaths.", capital_effect: -10, population_effect: 0, stability_effect: 0, resources_effect: -250, nation_id: 1)
event6.responses.create(description: "Do nothing. Let them fend for themselves. The market will correct for the disaster. Climate change isn't real. Bottled water tastes better anyway. Advisers say this decision will maintain capital.", capital_effect: 0, population_effect: -100000, stability_effect: -0.2, resources_effect: -500, nation_id: 1)

event2 = Event.create({name: "Stock Market Crash. Panic reins supreme. Population worries about retirement resources."})
event2.responses.create(description: "Halt the markets for the day and give an inspiring speech. Work with Congress to create a stimulus package. Advisers say this will save capital.", capital_effect: 50, population_effect: 250000, stability_effect: 0.1, resources_effect: 1000, nation_id: 1)
event2.responses.create(description: "Give pretty okay speech at Goldman Sachs. Bailout the banks. Experts say this will help maintain stability.", capital_effect: -10, population_effect: 0, stability_effect: 0, resources_effect: -750, nation_id: 1)
event2.responses.create(description: "Dips and valleys are a part of a healthy economy. Ride the wave, fellas. Advisers say population size will be unaffected by this.", capital_effect: -50, population_effect: 0, stability_effect: -0.2, resources_effect: -1000, nation_id: 1)

event7 = Event.create({name: "Every woman in your nation goes on strike. Demands include equal pay and a break from mansplaining."})
event7.responses.create(description: "Give an inspiring speech. Work with government to pass equal rights bill (FINALLY). Advisers say this will generate capital.", capital_effect: 55, population_effect: 250000, stability_effect: 0.1, resources_effect: 1000, nation_id: 1)
event7.responses.create(description: "Give pretty okay speech with Megyn Kelly. Promise to work on paid leave for childbirth. Experts say this will help maintain stability.", capital_effect: -10, population_effect: 0, stability_effect: 0, resources_effect: -750, nation_id: 1)
event7.responses.create(description: "Start Men's Rights Campaign, subversively. Take away their birth control. Advisers say this will maintain resources, since half the population is on strike.", capital_effect: -50, population_effect: -500000, stability_effect: -0.2, resources_effect: 0, nation_id: 1)

event3 = Event.create({name: "Scientists discover a cure for the deadly Donald Trump Virus. Need funding for vaccine distribution."})
event3.responses.create(description: "Grant funding to the scientists, and set up a special panel to study the terrifying effects of this disease. Experts say this will save lives.", capital_effect: 50, population_effect: 250000, stability_effect: 0.1, resources_effect: 1000, nation_id: 1)
event3.responses.create(description: "Maintain current funding level and encourage private investment. Advisers say this will maintain population level.", capital_effect: -10, population_effect: 0, stability_effect: 0, resources_effect: -500, nation_id: 1)
event3.responses.create(description: "Vaccines cause austism, don't you know? Divert funds to charter schools instead. Advisers say this will maintain GDP.", capital_effect: 0, population_effect: -100000, stability_effect: -0.2, resources_effect: -1000, nation_id: 1)

event8 = Event.create({name: "Scientists create artificial photosynthesis, which will take carbon dioxide out of the atmosphere. They need funding to do it on a larger scale."})
event8.responses.create(description: "Grant funding to the scientists, and immediately implement the technology nation wide. Experts say this will save lives.", capital_effect: 50, population_effect: 250000, stability_effect: 0.1, resources_effect: 1000, nation_id: 1)
event8.responses.create(description: "Maintain current funding level and encourage private investment. Advisers say this will maintain population level.", capital_effect: -10, population_effect: 0, stability_effect: 0, resources_effect: -500, nation_id: 1)
event8.responses.create(description: "That's not natural! Plus, photosynthesis causes rabies. And climate change isn't real. I love carbon dioxide. Divert public funds to defense contractors instead. Advisers say this will maintain GDP.", capital_effect: 0, population_effect: -100000, stability_effect: -0.2, resources_effect: -1000, nation_id: 1)

event4 = Event.create({name: "New rocket has gone over budget. Local company requests additional government support. Space travel to Mars would inspire the population."})
event4.responses.create(description: "Grant funding and set goal to travel to Mars by 2030. Give classic speech about doing things because they are hard. The masses love it.", capital_effect: 50, population_effect: 250000, stability_effect: 0.1, resources_effect: 1000, nation_id: 1)
event4.responses.create(description: "Set goal to go to Mars by 2050. Encourage private investment. Watch the movie 'The Martian.' Experts say this will maintain stability.", capital_effect: -10, population_effect: 0, stability_effect: 0, resources_effect: -1000, nation_id: 1)
event4.responses.create(description: "Mars is fictional, the Earth is the only real planet. Also, it's flat. Divert funds to voter suppression efforts. Advisers say that this will not effect population. Plus, you're the only person in existence so you're not too concerned about the population anyways.", capital_effect: -50, population_effect: 0, stability_effect: -0.2, resources_effect: -1000, nation_id: 1)

event9 = Event.create({name: "Your country has been selected to host the next Olympics. You need to choose a firm to build the necessary infrastructure."})
event9.responses.create(description: "Choose company that will build sustainable infrastructure that will last for years, and have the ability to be repurposed. It will cost a bit more, but is the most popular design.", capital_effect: -10, population_effect: 250000, stability_effect: 0.1, resources_effect: 1000, nation_id: 1)
event9.responses.create(description: "Choose company that stays on a budget. Focus on supporting athlete development so that your nation can kick ass at the event. Experts say this will improve stability.", capital_effect: 0, population_effect: 0, stability_effect: 0.2, resources_effect: -1000, nation_id: 1)
event9.responses.create(description: "Go with the lowest bidder. Encourage contractor to pay less than minimum wage under the table to workers. Experts say this will save capital.", capital_effect: 0, population_effect: -50000, stability_effect: -0.2, resources_effect: -1000, nation_id: 1)

event10 = Event.create({name: "Artificial Intelligence becomes real!"})
event10.responses.create(description: "Incorporate machines into society. Using the supreme intelligence of the machines combined with the emotional depth of humans, work together towards a better society. Feelings are good.", capital_effect: -10, population_effect: 250000, stability_effect: 0.2, resources_effect: 1000, nation_id: 1)
event10.responses.create(description: "Incorporate machines into society since they can make human lives easier. People need more drivers and personal chefs, right? People get used to having company and stop making new friends. Advisers say the current population will be maintained.", capital_effect: 0, population_effect: 0, stability_effect: 0, resources_effect: -500, nation_id: 1)
event10.responses.create(description: "Wage war on the machines. Humans are the superior race. Experts say this will maintain capital.", capital_effect: 0, population_effect: -50000, stability_effect: -0.2, resources_effect: -1000, nation_id: 1)
